-- Carga directa del stock real de Cocina (PDF "09-07-26 STOCK - 1 STOCK
-- INICIAL"). El importador por Excel no se pudo completar desde el
-- navegador del usuario, así que se carga por SQL directo en su lugar -
-- mismos 190 insumos/cantidades que tenía el archivo generado antes.
-- Idempotente: si se corre dos veces, no duplica productos ni pisa
-- cantidades ya cargadas por otra vía con valores distintos a los de acá
-- (usa el mismo valor siempre, así que un re-run deja todo igual).

with product_data (name, category_name, quantity) as (
  values
    ('Bondiola fraccionada', 'Producción', 120),
    ('Cantimpalo fraccionado', 'Producción', 135),
    ('Cebolla blanca y morada salteada', 'Producción', 1935),
    ('Cebolla caramelizada', 'Producción', 0),
    ('Cebolla de verdeo cortado', 'Producción', 0),
    ('Chutney de tomate', 'Producción', 0),
    ('Crema de hongos', 'Producción', 0),
    ('Guacamole', 'Producción', 0),
    ('Hamburguesas x 100gr', 'Producción', 0),
    ('Hongos salteados', 'Producción', 0),
    ('Jamon cocido fraccionado', 'Producción', 280),
    ('Jamon crudo fraccionado', 'Producción', 155),
    ('Lactonesa clasica', 'Producción', 650),
    ('Lactonesa de pimientos', 'Producción', 585),
    ('Lactonesa de rucula', 'Producción', 0),
    ('Lactonesa de zanahoria', 'Producción', 0),
    ('Lactonesa picante', 'Producción', 410),
    ('Lomito ahumado fraccionado', 'Producción', 110),
    ('Morron cocinado', 'Producción', 0),
    ('Mortadela con pistacho fraccionado', 'Producción', 465),
    ('Panceta fraccionada (30gr)', 'Producción', 0),
    ('Panceta salteada', 'Producción', 165),
    ('Papas noisette marcadas', 'Producción', 0),
    ('Pizzas marcadas', 'Producción', 0),
    ('Pizzas masas napolitanas marcadas', 'Producción', 18),
    ('Prepizza frozzy marcada', 'Producción', 0),
    ('Queso crema con hierbas', 'Producción', 0),
    ('Queso criollo fraccionado', 'Producción', 365),
    ('Queso muzarella fracción x 180 gr', 'Producción', 3800),
    ('Queso pategras fraccionado', 'Producción', 565),
    ('Queso pepato fraccionado', 'Producción', 0),
    ('Queso provolone x 30 gramos', 'Producción', 200),
    ('Queso sardo rallado granjera', 'Producción', 0),
    ('Queso tybo en cubos macerado con aceite y especias', 'Producción', 0),
    ('Queso tybo fraccionado', 'Producción', 0),
    ('Salame fraccionado', 'Producción', 0),
    ('Salsa chimichurri', 'Producción', 505),
    ('Salsa criolla', 'Producción', 0),
    ('Salsa mil islas', 'Producción', 0),
    ('Salsa para pizza', 'Producción', 3000),
    ('Salsa pesto', 'Producción', 505),
    ('Tomate cherry con aceite y albahaca', 'Producción', 1190),
    ('Tomate cortado', 'Producción', 0),
    ('Babaganoush', 'Aderezos', 540),
    ('Barbacoa', 'Aderezos', 970),
    ('Chucrut', 'Aderezos', 530),
    ('Ketchup', 'Aderezos', 0),
    ('Mayonesa', 'Aderezos', 0),
    ('Miel de monte', 'Aderezos', 310),
    ('Mostaza', 'Aderezos', 0),
    ('Mostaza dijon', 'Aderezos', 280),
    ('Salsa de aji picante', 'Aderezos', 1290),
    ('Salsa golf', 'Aderezos', 0),
    ('Salsa jalapeño ahumada', 'Aderezos', 190),
    ('Salsa jalapeño rojos', 'Aderezos', 190),
    ('Salsa jalapeño verde', 'Aderezos', 190),
    ('Ajo', 'Verdulería', 1),
    ('Albahaca fresca', 'Verdulería', 0),
    ('Berenjena', 'Verdulería', 0),
    ('Cebolla blanca', 'Verdulería', 18),
    ('Cebolla morada', 'Verdulería', 0),
    ('Cebolla verdeo', 'Verdulería', 1),
    ('Champiñones', 'Verdulería', 0),
    ('Hoja de espinaca', 'Verdulería', 0),
    ('Hoja de lechuga', 'Verdulería', 0),
    ('Hoja de perejil', 'Verdulería', 1),
    ('Hoja de rucula', 'Verdulería', 1),
    ('Hoja de verdeo', 'Verdulería', 0),
    ('Huevos', 'Verdulería', 30),
    ('Kale', 'Verdulería', 2),
    ('Limon', 'Verdulería', 1),
    ('Morron rojo', 'Verdulería', 2),
    ('Palta', 'Verdulería', 0),
    ('Pepino', 'Verdulería', 2),
    ('Repollo', 'Verdulería', 0),
    ('Tomate cherry', 'Verdulería', 0),
    ('Tomate perita', 'Verdulería', 0),
    ('Uva verde', 'Verdulería', 0),
    ('Uva violeta', 'Verdulería', 0),
    ('Zanahoria', 'Verdulería', 1),
    ('Masas de pizzas frozzy', 'Masas y Panes', 0),
    ('Masa de pizzetas', 'Masas y Panes', 0),
    ('Masas napolitanas naples', 'Masas y Panes', 110),
    ('Pan de hamburguesas (strobel)', 'Masas y Panes', 0),
    ('Pan de lomo delicias argentinas (ciabattas)', 'Masas y Panes', 22),
    ('Pan de masa madre', 'Masas y Panes', 0),
    ('Pan de pata (chacabuco)', 'Masas y Panes', 0),
    ('Pan baguette', 'Masas y Panes', 0),
    ('Bastones mozarella', 'Congelados', 0),
    ('Bondiola desmenuzada', 'Congelados', 0),
    ('Brochette de pollo', 'Congelados', 0),
    ('Empanadas de bondiola (punto producción)', 'Congelados', 4),
    ('Empanadas criollas', 'Congelados', 0),
    ('Empanadas de cebolla y queso', 'Congelados', 0),
    ('Empanadas de jamon y queso', 'Congelados', 0),
    ('Empanadas de vacio (punto producción)', 'Congelados', 0),
    ('Falafel', 'Congelados', 0),
    ('Finger de pollo', 'Congelados', 2),
    ('Milanesa de carne', 'Congelados', 0),
    ('Milanesa de pollo', 'Congelados', 0),
    ('Papas baston', 'Congelados', 0),
    ('Papas en cuña', 'Congelados', 0),
    ('Papas nosiette x10kg', 'Congelados', 7),
    ('Pata flambeada', 'Congelados', 10800),
    ('Pechuga de pollo', 'Congelados', 2),
    ('Pizzas c/tac (cresfood)', 'Congelados', 6),
    ('Salchicha parrillera', 'Congelados', 23),
    ('Sorrentinos', 'Congelados', 23),
    ('Sorrentinos osobuco', 'Congelados', 11),
    ('Sorrentinos verdura', 'Congelados', 11),
    ('Sorrentinos pollo y verdura', 'Congelados', 9),
    ('Sorrentinos de pimientos', 'Congelados', 11),
    ('Sorrentinos de bondiola', 'Congelados', 0),
    ('Bondiola', 'Quesos, Lácteos y Fiambres', 350),
    ('Cantimpalo', 'Quesos, Lácteos y Fiambres', 1875),
    ('Cheddar en fetas', 'Quesos, Lácteos y Fiambres', 0),
    ('Cheddar pouch la tonadita x 3kg', 'Quesos, Lácteos y Fiambres', 1455),
    ('Lomito ahumado', 'Quesos, Lácteos y Fiambres', 400),
    ('Jamon cocido calchaqui x 5kg', 'Quesos, Lácteos y Fiambres', 2720),
    ('Jamon crudo marca', 'Quesos, Lácteos y Fiambres', 2435),
    ('Manteca', 'Quesos, Lácteos y Fiambres', 0),
    ('Mortadela con pistachos marca', 'Quesos, Lácteos y Fiambres', 1395),
    ('Muzarella x 10 kg', 'Quesos, Lácteos y Fiambres', 10),
    ('Muzzarella x 5 kg', 'Quesos, Lácteos y Fiambres', 0),
    ('Panceta ahumada 103', 'Quesos, Lácteos y Fiambres', 2080),
    ('Panceta ahumada nuevo munich x 2,150 kg', 'Quesos, Lácteos y Fiambres', 0),
    ('Provoleta nonna pia con cazuela', 'Quesos, Lácteos y Fiambres', 0),
    ('Provoleta nonna pia sin cazuela', 'Quesos, Lácteos y Fiambres', 15),
    ('Queso azul pouch', 'Quesos, Lácteos y Fiambres', 2),
    ('Queso crema pouch', 'Quesos, Lácteos y Fiambres', 6110),
    ('Queso criollo', 'Quesos, Lácteos y Fiambres', 900),
    ('Queso parmesano', 'Quesos, Lácteos y Fiambres', 0),
    ('Queso pategras', 'Quesos, Lácteos y Fiambres', 0),
    ('Queso pepato', 'Quesos, Lácteos y Fiambres', 1530),
    ('Queso sardo', 'Quesos, Lácteos y Fiambres', 0),
    ('Queso sardo las tres x 3.6 kg', 'Quesos, Lácteos y Fiambres', 0),
    ('Queso tybo colonia x kg', 'Quesos, Lácteos y Fiambres', 0),
    ('Queso tybo legendario x 4 kg', 'Quesos, Lácteos y Fiambres', 0),
    ('Salame', 'Quesos, Lácteos y Fiambres', 3),
    ('Salchichas alemanas frankfurter bratwurst', 'Quesos, Lácteos y Fiambres', 16),
    ('Salchichas alemanas mini weiner', 'Quesos, Lácteos y Fiambres', 0),
    ('Salchichas alemanas ridenwurst', 'Quesos, Lácteos y Fiambres', 16),
    ('Aceite de girasol x 5 lts', 'Almacén', 7),
    ('Aceite de oliva olivares del señor 5l', 'Almacén', 2),
    ('Aceite grano de oro 900ml', 'Almacén', 32),
    ('Aceituna fileteada', 'Almacén', 0),
    ('Aceituna negra x 3 kg', 'Almacén', 1),
    ('Aceituna verde x 5 kg', 'Almacén', 1),
    ('Aceto balsamico 250ml', 'Almacén', 1),
    ('Azucar san agustin 1kg', 'Almacén', 1),
    ('Frutos secos', 'Almacén', 100),
    ('Garbanzo 500grs', 'Almacén', 0),
    ('Harina florencia 000 1kg', 'Almacén', 0),
    ('Leche entera tregar 1l', 'Almacén', 2),
    ('Nachos', 'Almacén', 0),
    ('Panko', 'Almacén', 0),
    ('Pan rayado', 'Almacén', 0),
    ('Tomate triturado corper 8kg', 'Almacén', 0),
    ('Tomate triturado finca de santiago 8 kg', 'Almacén', 6),
    ('Vinagre de alcohol', 'Almacén', 0),
    ('Aji triturado', 'Condimentos y Especias', 415),
    ('Condimento para pizza 500grs', 'Condimentos y Especias', 0),
    ('Albahaca', 'Condimentos y Especias', 730),
    ('Merken', 'Condimentos y Especias', 0),
    ('Oregano 500grs', 'Condimentos y Especias', 480),
    ('Pimenton ahumado', 'Condimentos y Especias', 70),
    ('Pimenton dulce', 'Condimentos y Especias', 0),
    ('Pimenton extra 20grs', 'Condimentos y Especias', 0),
    ('Pimienta negra 515grs', 'Condimentos y Especias', 0),
    ('Sal fina dos anclas 5kg', 'Condimentos y Especias', 13),
    ('Bia col 5lts 70', 'Limpieza', 2),
    ('Desengrasante 5lts', 'Limpieza', 2),
    ('Detergente 5lts', 'Limpieza', 3),
    ('Espoja acero grande broomy', 'Limpieza', 1),
    ('Lavandina 5lts', 'Limpieza', 0),
    ('Limpia vidrios 5lts', 'Limpieza', 0),
    ('Perfumina 5lts', 'Limpieza', 0),
    ('Rejillas linea 10bar', 'Limpieza', 2),
    ('Trapo de piso mr gris', 'Limpieza', 0),
    ('Bobina de film', 'Descartables', 0),
    ('Bobina de limpieza 20x400mt', 'Descartables', 1),
    ('Bolsa consorcio 90x120 x10u', 'Descartables', 5),
    ('Bolsas de corte 25x35', 'Descartables', 1),
    ('Cajas de lomo', 'Descartables', 80),
    ('Cajas de pizzas', 'Descartables', 90),
    ('Folex 20 x 25', 'Descartables', 0),
    ('Folex 25 x 35', 'Descartables', 1),
    ('Papel aluminio', 'Descartables', 4),
    ('Papel sulfito ck parafinado 30x35 x10kg', 'Descartables', 1),
    ('Pote dip degustacion 50c con tapa', 'Descartables', 1)
)
insert into products (name, category_id)
select pd.name, c.id
from product_data pd
join categories c on c.name = pd.category_name
where not exists (
  select 1 from products p where lower(btrim(p.name)) = lower(btrim(pd.name))
);

with product_data (name, category_name, quantity) as (
  values
    ('Bondiola fraccionada', 'Producción', 120),
    ('Cantimpalo fraccionado', 'Producción', 135),
    ('Cebolla blanca y morada salteada', 'Producción', 1935),
    ('Cebolla caramelizada', 'Producción', 0),
    ('Cebolla de verdeo cortado', 'Producción', 0),
    ('Chutney de tomate', 'Producción', 0),
    ('Crema de hongos', 'Producción', 0),
    ('Guacamole', 'Producción', 0),
    ('Hamburguesas x 100gr', 'Producción', 0),
    ('Hongos salteados', 'Producción', 0),
    ('Jamon cocido fraccionado', 'Producción', 280),
    ('Jamon crudo fraccionado', 'Producción', 155),
    ('Lactonesa clasica', 'Producción', 650),
    ('Lactonesa de pimientos', 'Producción', 585),
    ('Lactonesa de rucula', 'Producción', 0),
    ('Lactonesa de zanahoria', 'Producción', 0),
    ('Lactonesa picante', 'Producción', 410),
    ('Lomito ahumado fraccionado', 'Producción', 110),
    ('Morron cocinado', 'Producción', 0),
    ('Mortadela con pistacho fraccionado', 'Producción', 465),
    ('Panceta fraccionada (30gr)', 'Producción', 0),
    ('Panceta salteada', 'Producción', 165),
    ('Papas noisette marcadas', 'Producción', 0),
    ('Pizzas marcadas', 'Producción', 0),
    ('Pizzas masas napolitanas marcadas', 'Producción', 18),
    ('Prepizza frozzy marcada', 'Producción', 0),
    ('Queso crema con hierbas', 'Producción', 0),
    ('Queso criollo fraccionado', 'Producción', 365),
    ('Queso muzarella fracción x 180 gr', 'Producción', 3800),
    ('Queso pategras fraccionado', 'Producción', 565),
    ('Queso pepato fraccionado', 'Producción', 0),
    ('Queso provolone x 30 gramos', 'Producción', 200),
    ('Queso sardo rallado granjera', 'Producción', 0),
    ('Queso tybo en cubos macerado con aceite y especias', 'Producción', 0),
    ('Queso tybo fraccionado', 'Producción', 0),
    ('Salame fraccionado', 'Producción', 0),
    ('Salsa chimichurri', 'Producción', 505),
    ('Salsa criolla', 'Producción', 0),
    ('Salsa mil islas', 'Producción', 0),
    ('Salsa para pizza', 'Producción', 3000),
    ('Salsa pesto', 'Producción', 505),
    ('Tomate cherry con aceite y albahaca', 'Producción', 1190),
    ('Tomate cortado', 'Producción', 0),
    ('Babaganoush', 'Aderezos', 540),
    ('Barbacoa', 'Aderezos', 970),
    ('Chucrut', 'Aderezos', 530),
    ('Ketchup', 'Aderezos', 0),
    ('Mayonesa', 'Aderezos', 0),
    ('Miel de monte', 'Aderezos', 310),
    ('Mostaza', 'Aderezos', 0),
    ('Mostaza dijon', 'Aderezos', 280),
    ('Salsa de aji picante', 'Aderezos', 1290),
    ('Salsa golf', 'Aderezos', 0),
    ('Salsa jalapeño ahumada', 'Aderezos', 190),
    ('Salsa jalapeño rojos', 'Aderezos', 190),
    ('Salsa jalapeño verde', 'Aderezos', 190),
    ('Ajo', 'Verdulería', 1),
    ('Albahaca fresca', 'Verdulería', 0),
    ('Berenjena', 'Verdulería', 0),
    ('Cebolla blanca', 'Verdulería', 18),
    ('Cebolla morada', 'Verdulería', 0),
    ('Cebolla verdeo', 'Verdulería', 1),
    ('Champiñones', 'Verdulería', 0),
    ('Hoja de espinaca', 'Verdulería', 0),
    ('Hoja de lechuga', 'Verdulería', 0),
    ('Hoja de perejil', 'Verdulería', 1),
    ('Hoja de rucula', 'Verdulería', 1),
    ('Hoja de verdeo', 'Verdulería', 0),
    ('Huevos', 'Verdulería', 30),
    ('Kale', 'Verdulería', 2),
    ('Limon', 'Verdulería', 1),
    ('Morron rojo', 'Verdulería', 2),
    ('Palta', 'Verdulería', 0),
    ('Pepino', 'Verdulería', 2),
    ('Repollo', 'Verdulería', 0),
    ('Tomate cherry', 'Verdulería', 0),
    ('Tomate perita', 'Verdulería', 0),
    ('Uva verde', 'Verdulería', 0),
    ('Uva violeta', 'Verdulería', 0),
    ('Zanahoria', 'Verdulería', 1),
    ('Masas de pizzas frozzy', 'Masas y Panes', 0),
    ('Masa de pizzetas', 'Masas y Panes', 0),
    ('Masas napolitanas naples', 'Masas y Panes', 110),
    ('Pan de hamburguesas (strobel)', 'Masas y Panes', 0),
    ('Pan de lomo delicias argentinas (ciabattas)', 'Masas y Panes', 22),
    ('Pan de masa madre', 'Masas y Panes', 0),
    ('Pan de pata (chacabuco)', 'Masas y Panes', 0),
    ('Pan baguette', 'Masas y Panes', 0),
    ('Bastones mozarella', 'Congelados', 0),
    ('Bondiola desmenuzada', 'Congelados', 0),
    ('Brochette de pollo', 'Congelados', 0),
    ('Empanadas de bondiola (punto producción)', 'Congelados', 4),
    ('Empanadas criollas', 'Congelados', 0),
    ('Empanadas de cebolla y queso', 'Congelados', 0),
    ('Empanadas de jamon y queso', 'Congelados', 0),
    ('Empanadas de vacio (punto producción)', 'Congelados', 0),
    ('Falafel', 'Congelados', 0),
    ('Finger de pollo', 'Congelados', 2),
    ('Milanesa de carne', 'Congelados', 0),
    ('Milanesa de pollo', 'Congelados', 0),
    ('Papas baston', 'Congelados', 0),
    ('Papas en cuña', 'Congelados', 0),
    ('Papas nosiette x10kg', 'Congelados', 7),
    ('Pata flambeada', 'Congelados', 10800),
    ('Pechuga de pollo', 'Congelados', 2),
    ('Pizzas c/tac (cresfood)', 'Congelados', 6),
    ('Salchicha parrillera', 'Congelados', 23),
    ('Sorrentinos', 'Congelados', 23),
    ('Sorrentinos osobuco', 'Congelados', 11),
    ('Sorrentinos verdura', 'Congelados', 11),
    ('Sorrentinos pollo y verdura', 'Congelados', 9),
    ('Sorrentinos de pimientos', 'Congelados', 11),
    ('Sorrentinos de bondiola', 'Congelados', 0),
    ('Bondiola', 'Quesos, Lácteos y Fiambres', 350),
    ('Cantimpalo', 'Quesos, Lácteos y Fiambres', 1875),
    ('Cheddar en fetas', 'Quesos, Lácteos y Fiambres', 0),
    ('Cheddar pouch la tonadita x 3kg', 'Quesos, Lácteos y Fiambres', 1455),
    ('Lomito ahumado', 'Quesos, Lácteos y Fiambres', 400),
    ('Jamon cocido calchaqui x 5kg', 'Quesos, Lácteos y Fiambres', 2720),
    ('Jamon crudo marca', 'Quesos, Lácteos y Fiambres', 2435),
    ('Manteca', 'Quesos, Lácteos y Fiambres', 0),
    ('Mortadela con pistachos marca', 'Quesos, Lácteos y Fiambres', 1395),
    ('Muzarella x 10 kg', 'Quesos, Lácteos y Fiambres', 10),
    ('Muzzarella x 5 kg', 'Quesos, Lácteos y Fiambres', 0),
    ('Panceta ahumada 103', 'Quesos, Lácteos y Fiambres', 2080),
    ('Panceta ahumada nuevo munich x 2,150 kg', 'Quesos, Lácteos y Fiambres', 0),
    ('Provoleta nonna pia con cazuela', 'Quesos, Lácteos y Fiambres', 0),
    ('Provoleta nonna pia sin cazuela', 'Quesos, Lácteos y Fiambres', 15),
    ('Queso azul pouch', 'Quesos, Lácteos y Fiambres', 2),
    ('Queso crema pouch', 'Quesos, Lácteos y Fiambres', 6110),
    ('Queso criollo', 'Quesos, Lácteos y Fiambres', 900),
    ('Queso parmesano', 'Quesos, Lácteos y Fiambres', 0),
    ('Queso pategras', 'Quesos, Lácteos y Fiambres', 0),
    ('Queso pepato', 'Quesos, Lácteos y Fiambres', 1530),
    ('Queso sardo', 'Quesos, Lácteos y Fiambres', 0),
    ('Queso sardo las tres x 3.6 kg', 'Quesos, Lácteos y Fiambres', 0),
    ('Queso tybo colonia x kg', 'Quesos, Lácteos y Fiambres', 0),
    ('Queso tybo legendario x 4 kg', 'Quesos, Lácteos y Fiambres', 0),
    ('Salame', 'Quesos, Lácteos y Fiambres', 3),
    ('Salchichas alemanas frankfurter bratwurst', 'Quesos, Lácteos y Fiambres', 16),
    ('Salchichas alemanas mini weiner', 'Quesos, Lácteos y Fiambres', 0),
    ('Salchichas alemanas ridenwurst', 'Quesos, Lácteos y Fiambres', 16),
    ('Aceite de girasol x 5 lts', 'Almacén', 7),
    ('Aceite de oliva olivares del señor 5l', 'Almacén', 2),
    ('Aceite grano de oro 900ml', 'Almacén', 32),
    ('Aceituna fileteada', 'Almacén', 0),
    ('Aceituna negra x 3 kg', 'Almacén', 1),
    ('Aceituna verde x 5 kg', 'Almacén', 1),
    ('Aceto balsamico 250ml', 'Almacén', 1),
    ('Azucar san agustin 1kg', 'Almacén', 1),
    ('Frutos secos', 'Almacén', 100),
    ('Garbanzo 500grs', 'Almacén', 0),
    ('Harina florencia 000 1kg', 'Almacén', 0),
    ('Leche entera tregar 1l', 'Almacén', 2),
    ('Nachos', 'Almacén', 0),
    ('Panko', 'Almacén', 0),
    ('Pan rayado', 'Almacén', 0),
    ('Tomate triturado corper 8kg', 'Almacén', 0),
    ('Tomate triturado finca de santiago 8 kg', 'Almacén', 6),
    ('Vinagre de alcohol', 'Almacén', 0),
    ('Aji triturado', 'Condimentos y Especias', 415),
    ('Condimento para pizza 500grs', 'Condimentos y Especias', 0),
    ('Albahaca', 'Condimentos y Especias', 730),
    ('Merken', 'Condimentos y Especias', 0),
    ('Oregano 500grs', 'Condimentos y Especias', 480),
    ('Pimenton ahumado', 'Condimentos y Especias', 70),
    ('Pimenton dulce', 'Condimentos y Especias', 0),
    ('Pimenton extra 20grs', 'Condimentos y Especias', 0),
    ('Pimienta negra 515grs', 'Condimentos y Especias', 0),
    ('Sal fina dos anclas 5kg', 'Condimentos y Especias', 13),
    ('Bia col 5lts 70', 'Limpieza', 2),
    ('Desengrasante 5lts', 'Limpieza', 2),
    ('Detergente 5lts', 'Limpieza', 3),
    ('Espoja acero grande broomy', 'Limpieza', 1),
    ('Lavandina 5lts', 'Limpieza', 0),
    ('Limpia vidrios 5lts', 'Limpieza', 0),
    ('Perfumina 5lts', 'Limpieza', 0),
    ('Rejillas linea 10bar', 'Limpieza', 2),
    ('Trapo de piso mr gris', 'Limpieza', 0),
    ('Bobina de film', 'Descartables', 0),
    ('Bobina de limpieza 20x400mt', 'Descartables', 1),
    ('Bolsa consorcio 90x120 x10u', 'Descartables', 5),
    ('Bolsas de corte 25x35', 'Descartables', 1),
    ('Cajas de lomo', 'Descartables', 80),
    ('Cajas de pizzas', 'Descartables', 90),
    ('Folex 20 x 25', 'Descartables', 0),
    ('Folex 25 x 35', 'Descartables', 1),
    ('Papel aluminio', 'Descartables', 4),
    ('Papel sulfito ck parafinado 30x35 x10kg', 'Descartables', 1),
    ('Pote dip degustacion 50c con tapa', 'Descartables', 1)
)
insert into product_stock (product_id, location_id, quantity, min_stock)
select p.id, l.id, pd.quantity, 0
from product_data pd
join products p on lower(btrim(p.name)) = lower(btrim(pd.name))
cross join locations l
where l.name = 'Cocina'
on conflict (product_id, location_id) do update set quantity = excluded.quantity;
